<template>
    <v-layout>
        <v-flex xs12>
            <v-img
                    :src="require('../assets/img/Time_bomb_regles/Time_bomb_regles-01.jpg')"
            ></v-img>
            <v-img
                    :src="require('../assets/img/Time_bomb_regles/Time_bomb_regles-02.jpg')"
            ></v-img>
            <v-img
                    :src="require('../assets/img/Time_bomb_regles/Time_bomb_regles-02.jpg')"
            ></v-img>
            <v-img
                    :src="require('../assets/img/Time_bomb_regles/Time_bomb_regles-03.jpg')"
            ></v-img>
            <v-img
                    :src="require('../assets/img/Time_bomb_regles/Time_bomb_regles-04.jpg')"
            ></v-img>
            <v-img
                    :src="require('../assets/img/Time_bomb_regles/Time_bomb_regles-05.jpg')"
            ></v-img>
            <v-img
                    :src="require('../assets/img/Time_bomb_regles/Time_bomb_regles-06.jpg')"
            ></v-img>
            <v-img
                    :src="require('../assets/img/Time_bomb_regles/Time_bomb_regles-07.jpg')"
            ></v-img>
            <v-img
                    :src="require('../assets/img/Time_bomb_regles/Time_bomb_regles-08.jpg')"
            ></v-img>
            <v-img
                    :src="require('../assets/img/Time_bomb_regles/Time_bomb_regles-09.jpg')"
            ></v-img>
            <v-img
                    :src="require('../assets/img/Time_bomb_regles/Time_bomb_regles-10.jpg')"
            ></v-img>
            <v-img
                    :src="require('../assets/img/Time_bomb_regles/Time_bomb_regles-11.jpg')"
            ></v-img>
            <v-img
                    :src="require('../assets/img/Time_bomb_regles/Time_bomb_regles-12.jpg')"
            ></v-img>
        </v-flex>
    </v-layout>
</template>

<script>
  export default {
    components: {}
  };
</script>
